use colored::Colorize;
use std::path::Path;

const LEFTHOOK_CONFIG: &str = r#"# Generated by ksec init
# https://github.com/evilmartians/lefthook

pre-commit:
  parallel: true
  commands:
    gitleaks:
      run: gitleaks detect --source . --no-banner --verbose
      fail_text: "secrets detected — run `ksec secrets` for details"

    bun-audit:
      glob: "package.json"
      run: bun audit
      fail_text: "vulnerable dependencies — run `ksec deps` for details"

    opengrep:
      glob: "*.{ts,tsx,js,jsx,py,go,rs}"
      run: opengrep scan --config auto --quiet .
      fail_text: "SAST findings — run `ksec sast` for details"

pre-push:
  parallel: true
  commands:
    trivy:
      run: trivy fs --scanners vuln --severity HIGH,CRITICAL --exit-code 1 .
      fail_text: "high/critical vulnerabilities — run `ksec deps` for details"

    trufflehog:
      run: trufflehog filesystem . --no-update --fail
      fail_text: "secrets detected (trufflehog) — run `ksec secrets` for details"
"#;

pub fn run_init(force: bool) {
    let path = Path::new("lefthook.yml");

    if path.exists() && !force {
        println!(
            "  {} lefthook.yml already exists — use {} to overwrite",
            "⚠".yellow(),
            "--force".bold()
        );
        return;
    }

    match std::fs::write(path, LEFTHOOK_CONFIG) {
        Ok(()) => {
            println!("  {} lefthook.yml generated", "✓".green());
            println!();
            println!("  next steps:");
            println!("    1. Install lefthook: {}", "go install github.com/evilmartians/lefthook@latest".dimmed());
            println!("    2. Activate hooks:   {}", "lefthook install".dimmed());
            println!();
            println!(
                "  hooks: {} (pre-commit), {} (pre-push)",
                "gitleaks + bun-audit + opengrep".bold(),
                "trivy + trufflehog".bold()
            );
        }
        Err(e) => {
            eprintln!("  {} failed to write lefthook.yml: {}", "✗".red(), e);
        }
    }
}
