use colored::Colorize;
use std::path::Path;

const LEFTHOOK_CONFIG: &str = r#"# Generated by ksec init
# https://github.com/evilmartians/lefthook

pre-commit:
  parallel: true
  commands:
    ksec-secrets:
      run: ksec secrets --min-severity high .
      fail_text: "secrets detected — run `ksec secrets` for details"

    ksec-sast:
      glob: "*.{ts,tsx,js,jsx,py,php,go,rs,rb}"
      run: ksec sast --min-severity high .
      fail_text: "SAST findings — run `ksec sast` for details"

    ksec-obfuscation:
      glob: "*.config.{js,mjs,cjs,ts}"
      run: ksec obfuscation .
      fail_text: "obfuscated code detected — run `ksec obfuscation` for details"

pre-push:
  parallel: true
  commands:
    ksec-full:
      run: ksec scan --min-severity high .
      fail_text: "security findings — run `ksec scan` for details"
"#;

pub fn run_init(force: bool) {
    let path = Path::new("lefthook.yml");

    if path.exists() && !force {
        println!(
            "  {} lefthook.yml already exists — use {} to overwrite",
            "⚠".yellow(),
            "--force".bold()
        );
        return;
    }

    match std::fs::write(path, LEFTHOOK_CONFIG) {
        Ok(()) => {
            println!("  {} lefthook.yml generated", "✓".green());
            println!();
            println!("  pre-commit: {} + {} + {}",
                "secrets".bold(), "sast".bold(), "obfuscation".bold());
            println!("  pre-push:   {}",
                "full scan (all 5 scanners)".bold());
            println!();
            println!("  next steps:");
            println!("    1. Install lefthook: {}", "go install github.com/evilmartians/lefthook@latest".dimmed());
            println!("    2. Activate hooks:   {}", "lefthook install".dimmed());
        }
        Err(e) => {
            eprintln!("  {} failed to write lefthook.yml: {}", "✗".red(), e);
        }
    }
}
